### ISSUE TITLE
Missing type="text/css" in stylesheet declaration

### ISSUE THREAD

**Issue by lvs-training** [aneagoie/aneagoie.github.io#1]
`<link href="style.css" rel="stylesheet">`

should be 

`<link rel="stylesheet" type="text/css" href="style.css">`

In my case the website was working locally but once uploaded on github the subscribe button was stucked on the left side. Fixed after adding  the type in the CSS declaration.

**Comment by aneagoie** [comment]
Hey, great catch @lvs-training, want to submit a pull request for the fix and I can merge it in?

**Comment by lvs-training** [comment]
I'm glad that i can contribute even with this very small change. Just made the pull request, I hope i did it well since it's my first pull request on Github :)

**Comment by aneagoie** [comment]
Just merged it! Congrats on your first successful Pull request!
